### ISSUE TITLE
Disorders remains as "loading..." when loading from .json file

### ISSUE THREAD

**Issue by shermanlo77** [aehrc/open-pedigree#8]
Branch: [feature/terminology](https://github.com/aehrc/open-pedigree/tree/feature/terminology)

When saving the tree using the GA4GH FHIR option, loading the tree again shows the disorders as "loading...". This is probably a bug due to #7

## Notes

Following the [instructions](https://github.com/aehrc/open-pedigree/blob/feature/terminology/terminology.md) and implementing the FHIR Terminology by editing the `apps.js` to be

```javascript
document.observe('dom:loaded', function () {
  editor = new PedigreeEditor({
    'disorderOptions': {
      'type': 'FHIR',
      'validIdRegex': /\d+/,
      'fhirBaseUrl': 'https://r4.ontoserver.csiro.au/fhir',
      'codeSystem': 'http://snomed.info/sct',
      'valueSet': 'http://snomed.info/sct?fhir_vs=refset/32570581000036105'
    },
  });
});
```

The software does indeed correctly look up disorders. It also saves custom disorders and loads them again from save. When loading, it was observed "loading..." does appear but after a while, the correct disorders replace it

**Comment by dconlan** [comment]
When the pedigree is loaded only the code part of the value is used. The entry is added with a display of 'loading...', but the system will then call the terminology lookupTerm method, which does to the call to the remote system. If the lookup is successful then the display is changed to the loaded value. I'm not sure what happens if it fails, probably stay as 'loading...'
